version: '3'

services:
  app:
    build:
      context: .  # Указываем, что Dockerfile находится в текущей папке
    depends_on:
      - postgres
    ports:
      - "8080:8080"  # Пробрасываем порт для доступа к приложению
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"